let scripts=[]; let editing=-1;
const $=id=>document.getElementById(id); const status=t=>$('status').textContent=t;
function normalize(x){return {title:String(x.title||''),male:+x.male||0,female:+x.female||0,any:+x.any||0,minutes:+x.minutes||0,genres:Array.isArray(x.genres)?x.genres:[],url:String(x.url||''),new:Boolean(x.new)}}
function render(){const list=$('list'); list.innerHTML=''; if(!scripts.length){list.innerHTML='<p class="note">台本がありません。</p>';return} scripts.forEach((s,i)=>{const d=document.createElement('div');d.className='adminItem';const info=document.createElement('div');const strong=document.createElement('strong');strong.textContent=s.title;const small=document.createElement('small');small.textContent=`${s.male+s.female+s.any}人（男${s.male}・女${s.female}・不問${s.any}）｜${s.genres.join('・')}｜約${s.minutes}分`;info.append(strong,small);const a=document.createElement('div');a.className='actions';const e=document.createElement('button');e.textContent='編集';e.onclick=()=>edit(i);const del=document.createElement('button');del.textContent='削除';del.className='danger';del.onclick=()=>{if(confirm(`「${s.title}」を削除しますか？`)){scripts.splice(i,1);if(editing===i)reset();render();status('削除しました。最後に scripts.json を保存してください。')}};a.append(e,del);d.append(info,a);list.append(d)})}
function reset(){editing=-1;$('formTitle').textContent='台本を新規登録';$('save').textContent='新規登録する';$('cancel').hidden=true;['title','genres','url'].forEach(x=>$(x).value='');$('male').value=0;$('female').value=0;$('any').value=0;$('minutes').value=10}
function edit(i){editing=i;const s=scripts[i];$('formTitle').textContent='台本を編集';$('save').textContent='変更を保存';$('cancel').hidden=false;$('title').value=s.title;$('male').value=s.male;$('female').value=s.female;$('any').value=s.any;$('minutes').value=s.minutes;$('genres').value=s.genres.join(', ');$('url').value=s.url;scrollTo({top:document.querySelectorAll('.adminPanel')[1].offsetTop-20,behavior:'smooth'})}
$('save').onclick=()=>{const s={title:$('title').value.trim(),male:+$('male').value||0,female:+$('female').value||0,any:+$('any').value||0,minutes:+$('minutes').value||0,genres:$('genres').value.split(/[,、]/).map(x=>x.trim()).filter(Boolean),url:$('url').value.trim(),new:true};if(!s.title||!s.url||!s.minutes){alert('タイトル・時間・URLを入力してください。');return}if(editing>=0){s.new=scripts[editing].new;scripts[editing]=s;status('編集内容を保存しました。')}else{scripts.unshift(s);status('新しい台本を登録しました。')}reset();render()};$('cancel').onclick=reset;
function setData(data,msg){if(!Array.isArray(data))throw Error();scripts=data.map(normalize);reset();render();status(msg)}
$('loadSite').onclick=async()=>{try{const r=await fetch('data/scripts.json',{cache:'no-store'});setData(await r.json(),'現在のサイトデータを読み込みました。')}catch(e){status('読み込みに失敗しました。ファイル選択を使ってください。')}};
$('file').onchange=async e=>{try{setData(JSON.parse(await e.target.files[0].text()),'選択した scripts.json を読み込みました。')}catch(err){alert('JSONファイルを読み込めませんでした。')}};
async function autoLoad(){try{const r=await fetch('data/scripts.json?ts='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error();setData(await r.json(),'現在のサイトデータを自動で読み込みました。');}catch(e){status('サイトデータを自動で読み込めませんでした。「サイトのデータを読み込む」またはファイル選択を使ってください。')}}
$('download').onclick=()=>{const blob=new Blob([JSON.stringify(scripts,null,2)+'\n'],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='scripts.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);status('scripts.json を保存しました。GitHub の data/scripts.json と差し替えてください。')};autoLoad();
